### ISSUE TITLE
fatal errors for non existent profiles

### ISSUE THREAD

**Issue by propertunist** [iionly/Elgg_1.8_private_profiles#1]
i'm seeing errors in the php log when pages/profiles are accessed that don't exist - e.g. mysite.com/profile/nonexistentprofile

```
[error] 19197#0: *60922 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to a member function getGUID() on a non-object in /mypath/mod/private_profiles/start.php on line 105"
```

shouldn't this be handled more gracefully?

**Comment by iionly** [comment]
Fixed with version 1.8.5.
